### ISSUE TITLE
Peaq doesn't start at boot

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#107]
Works if I reload the integration manually. Don't know the reason, but here are some logs.

```
Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 22:38:43 (1 occurrences)
Last logged: 22:38:43

Error setting up entry peaqhvac for peaqhvac
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/peaqevcore/common/spotprice/nordpool.py", line 41, in setup
    self.hub.options.price.price_aware = False  # todo: composition
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigModel' object has no attribute 'price'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqhvac/__init__.py", line 44, in async_setup_entry
    hub = Hub(hass, huboptions)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqhvac/service/hub/hub.py", line 41, in __init__
    self.spotprice = SpotPriceFactory.create(hub=self, observer=self.observer, system=PeaqSystem.PeaqHvac, test=False, is_active=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/peaqevcore/common/spotprice/spotprice_factory.py", line 37, in create
    return SpotPriceFactory.sources[source](hub, observer, system, test, is_active)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/peaqevcore/common/spotprice/nordpool.py", line 17, in __init__
    super().__init__(hub=hub, source=NORDPOOL, system=system, test=test, is_active=is_active, observer=observer)
  File "/usr/local/lib/python3.12/site-packages/peaqevcore/common/spotprice/spotpricebase.py", line 33, in __init__
    self.setup()
  File "/usr/local/lib/python3.12/site-packages/peaqevcore/common/spotprice/nordpool.py", line 58, in setup
    self.hub.options.price.price_aware = False  # todo: composition todo: fix this
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigModel' object has no attribute 'price'
```

~~Logger: homeassistant.components.climate.const~~
~~Source: helpers/deprecation.py:206~~
~~integration: Climate (documentation, issues)~~
~~First occurred: 22:42:59 (2 occurrences)~~
~~Last logged: 22:42:59~~

~~SUPPORT_PRESET_MODE was used from peaqhvac, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'peaqhvac' custom integration
SUPPORT_TARGET_TEMPERATURE was used from peaqhvac, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'peaqhvac' custom integration~~

```
This error originated from a custom integration.

Logger: peaqevcore.common.spotprice.spotpricebase
Source: custom_components/peaqhvac/sensors/money_data_sensor.py:78
integration: peaqhvac (documentation, issues)
First occurred: 22:42:59 (1 occurrences)
Last logged: 22:42:59

Possible issue detected with <built-in method date of datetime.datetime object at 0x7f256565e580> in nordpool dates.
```

~~Logger: homeassistant.helpers.entity~~
~~Source: helpers/entity.py:1607~~
First occurred: 22:42:59 (1 occurrences)~~
~~Last logged: 22:42:59~~

~~Entity None (<class 'custom_components.peaqhvac.climate.PeaqClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please create a bug report at https://github.com/elden1337/hass-peaqhvac/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation~~

```
This error originated from a custom integration.

Logger: custom_components.peaqhvac.service.hvac.offset.offset_utils
Source: custom_components/peaqhvac/service/hvac/offset/offset_utils.py:25
integration: peaqhvac (documentation, issues)
First occurred: 22:43:00 (8 occurrences)
Last logged: 22:43:02

Error in flat_day_lower_tolerance: max() iterable argument is empty
```

**Comment by elden1337** [comment]
Moved unrelated logs to separate task #111

**Comment by elden1337** [comment]
one thing about that price-awarething (the top one). peaqhvac will wait for nordpool to startup before trying to start. If this is not happening i'm afraid it's out of my hands (it calls this error because it cannot find any nordpool-sensor on your HA).

**Comment by enoch85** [comment]
> peaqhvac will wait for nordpool to startup 

But I'm only using Energi Data Service. :/ Since that's supported shouldn't it look for both services before failing?

**Comment by elden1337** [comment]
> > peaqhvac will wait for nordpool to startup
> 
> But I'm only using Energi Data Service. :/ Since that's supported shouldn't it look for both services before failing?

yes, and it does. i was just sure you were using nordpool. same goes for that one. but for some reason it is not loaded when peaqhvac starts loading in your machine. my guess is that energidataservice claims to be ready before it actually is.

**Comment by elden1337** [comment]
Handled all these now. If issue remains please open new bugticket with more logs.
