### ISSUE TITLE
Peaqhvac fails to download from HACS

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#113]
```
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
integration: HACS (documentation, issues)
First occurred: 08:18:39 (1 occurrences)
Last logged: 08:18:39

<Integration elden1337/hass-peaqhvac> Failed to download https://github.com/elden1337/hass-peaqhvac/releases/download/tags/3.0.1/peaqhvaq.zip
```

The real link is: https://github.com/elden1337/hass-peaqhvac/releases/download/3.0.1/peaqhvac.zip 

I'm forced to manually upload, extract and enabled the plugin every time.

**Comment by elden1337** [comment]
stuck in what to do here. the url you are seeing there is not something constructed by me when integrating to slack, and the release cycle seems just fine. 
I also see that there are downloads on latest versions.

however, i do get the same issue as you and have also gotten reports from others. 
I think this is an issue with HACS itself, probably that github is changing url-structures.

**Comment by elden1337** [comment]
perhaps an issue here is needed https://github.com/hacs/integration/issues

**Comment by elden1337** [comment]
According to this file it is trying to construct the correct url

https://github.com/hacs/integration/blob/719c76453f2ace722143aedfca238dbd0f1c7399/custom_components/hacs/utils/url.py#L29

But yet your log from it clearly shows a wrongly constructed url (what version of hacs are you on?)

So im gonna have to dig deeper into that repo in that case, ie i dont know when that could be resolved.

**Comment by enoch85** [comment]
I'm on HACS 1.34.0.

Thanks for your efforts! <3

**Comment by enoch85** [comment]
> perhaps an issue here is needed https://github.com/hacs/integration/issues

So issue reported, and got this: https://github.com/hacs/integration/issues/3842#issuecomment-2200264596

**Comment by enoch85** [comment]
Finally, download works! :100:

**Comment by elden1337** [comment]
It is quite weird though since that typo has been there since 2022, but i guess a change on hacs made it mandatory.
