### ISSUE TITLE
peachvaq doesnt fetch prices from Energi Data Service 

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#125]
```
This error originated from a custom integration.

Logger: peaqevcore.common.spotprice.nordpool
Source: custom_components/peaqhvac/service/hub/hub.py:42
integration: peaqhvac (documentation, issues)
First occurred: 20:32:30 (2 occurrences)
Last logged: 20:32:30

There were no Spotprice-entities. Cannot continue. with price-awareness.
I was unable to get a Spotprice-entity. Cannot continue with price-awareness: 'ConfigModel' object has no attribute 'price'
```

### Not working version: 
3.1.1
### Working version: 
3.0.2 (at least it generates spot prices, but I never waited for offsets to start (it takes a while after a complete reboot)

### Tried downgrading
As soon as I downgrade to 3.0.2 it starts working again. The issue above also refers to `peaqevcore.common.spotprice.nordpool` which isn't installed (I only run Energi Data Service).

### Wrong attribute
Also looking at the attributes for peaq money controls, I find that it uses Nordpool, even though it's not installed.

![image](https://github.com/user-attachments/assets/b41151d0-4d79-4ea2-99a9-a42b82cad70d)

As a result, neither Offsets, or Water controls work. I think the main cause is the spot price awareness, but I'm only guessing.

### What I've tried so far:

1. Uninstall peaqhvaq completley, and rebooted, then set it up from scratch again
2. Installed Nordpool, but the Integration didn't work as expected, so I uninstalled it again.
3. Downgraded: look at the picture above, I got spot prices back.

**Comment by enoch85** [comment]
Also grepping for "energi" in the code shows nothing, but while "nordpool" shows up in various files.

```
daniel@xps9310:~/Downloads/hass-peaqhvac-main$ grep -r energi
README.MD:* [Nordpool](https://github.com/custom-components/nordpool) or [EnergiDataService](https://github.com/MTrab/energidataservice)
```

```
daniel@xps9310:~/Downloads/hass-peaqhvac-main$ grep -r nordpool
README.MD:* [Nordpool](https://github.com/custom-components/nordpool) or [EnergiDataService](https://github.com/MTrab/energidataservice)
custom_components/peaqhvac/manifest.json:      "nordpool",
custom_components/peaqhvac/service/hub/state_changes.py:        self.latest_nordpool_update = WaitTimer(timeout=300)
custom_components/peaqhvac/service/hub/state_changes.py:            or self.latest_nordpool_update.is_timeout()
custom_components/peaqhvac/service/hub/state_changes.py:            self.latest_nordpool_update.update()
```

**Comment by enoch85** [comment]
OK, seems to work with the latest upgrade. Thanks a lot!

![image](https://github.com/user-attachments/assets/f4488f8e-bdca-4f70-a545-8e3e4bf27ec6)

**Comment by enoch85** [comment]
Hmm, something is off. Now the price got lost again after a reboot...

**Comment by elden1337** [comment]
Try rebooting once more. Sometimes the package installer is weird in HA (the change is in my core lib so not in the code you have in HA)

**Comment by enoch85** [comment]
OK, it's back. 

![image](https://github.com/user-attachments/assets/e49800cd-9148-4243-80e0-81ec2e96ab92)
