### ISSUE TITLE
Fix temp extremas and temp trend offsets

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#127]
Clearly not working well:

![image](https://github.com/user-attachments/assets/3c27cd17-4de5-4789-ba69-72b16685bca9)

![image](https://github.com/user-attachments/assets/7a948ab5-c9b8-4846-a6ac-5fb55b6fe887)

![image](https://github.com/user-attachments/assets/0339c192-31bd-4c16-ae12-003b456659d4)

Set indoor temp is 20

**Comment by enoch85** [comment]
Hehe, noticed this now.

![Screenshot_2024-09-12-22-28-59-53_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/9a9513c9-1f1e-4ab0-8b8f-babbca83cd2c)

**Comment by elden1337** [comment]
> Hehe, noticed this now.
> 
> 
> 
> ![Screenshot_2024-09-12-22-28-59-53_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/9a9513c9-1f1e-4ab0-8b8f-babbca83cd2c)
> 
> 

Ok but this is not related. That thing is fixed in next release.

**Comment by enoch85** [comment]
Maybe this is related then? I don't remember if it's suppose to be like this?

![image](https://github.com/user-attachments/assets/375fad32-3560-4de2-b446-a96fb87f0fef)
![image](https://github.com/user-attachments/assets/cb52ae82-7002-4405-afbf-9fd0a5e8055b)

**Comment by elden1337** [comment]
I do not see any problem with that image of offsets. Please clarify.
