### ISSUE TITLE
Add back weather prognosis

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#130]
after HA changes we need to call a service to get the data.

**Comment by enoch85** [comment]
Thank you!!

**Comment by enoch85** [comment]
JFTR: 

```
tzinfo=datetime.timezone.utc)), WeatherObject(_DTstr='2024-10-16T11:00:00+00:00', WeatherCondition='cloudy', Temperature=11.6, Wind_Speed=26.21, Wind_Bearing=141, Precipitation_Probability=0, Precipitation=0.0, DT=datetime.datetime(2024, 10, 16, 11, 0,
```

Please note which I fo that is extracted from Openweather, are you looking for time date and temperature, or more factors?

**Comment by elden1337** [comment]
This is soley tested with the sensor weather... that works with the service to get prognosis fyi

**Comment by enoch85** [comment]
Hmm, is there some way to test that it actually works? I looked though some debug logs yesterday, but didn't find anything obvious.

**Comment by elden1337** [comment]
Weather here is currently too stable to influence the already set offsets. 

If you add the entity and get no errors after reboot it is counting with it.
