### ISSUE TITLE
hvaq maxes out at peak 

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#139]
Don't know why this happened, but 

![Screenshot_2024-11-11-17-45-28-63_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/415a5d33-c103-4dff-8017-67c2b13b510b)

Core
2024.11.1
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.2

**Comment by elden1337** [comment]
Because you let your dm fall too low i think. Peaq (or uplink) has no control over the immediate compressoe freq - power draw. 

The offset is at plus 1, indicating you have too cold indoors and that peaq is compensating for it. Every 0,2 under set temp on the avg/median value adds a step plus from the calculated. 
Plus, every 0,4 under set for the min temp value in your home adds an additionanl +1 on the offset.

**Comment by enoch85** [comment]
So what do you suggest as a solution? Raise the default offset by turning off Peaq and set a new "base offset"?

**Comment by enoch85** [comment]
![Screenshot_2024-11-11-18-58-55-26_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/c2e2c652-bedd-4e09-9a4e-617aa65e0bab)

What I find strange is that the temp haven't changed during the day, it even raised outside. Still it chose to heat the most during peaq.

**Comment by elden1337** [comment]
can you please show the offsets chart instead? the frequency is not peaq it's your settings with low dm that boosts it up like that.

**Comment by enoch85** [comment]
Sure! Here you go 👍🏼

![Screenshot_2024-11-11-19-49-06-42_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/7b40e02a-7a19-498b-96cf-95839a06004f)

**Comment by enoch85** [comment]
And temperature for the past days. The sudden peaks are when we used the Contura, and the drops are reboots of HAOS.

**Comment by enoch85** [comment]
Degree minutes for the same period 

![Screenshot_2024-11-11-19-56-47-74_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/731eea8a-42ec-4cae-a562-85df6cd6051f)

**Comment by enoch85** [comment]
> you let your dm fall too low

Can I affect the DM to never go as low? Should I change "Low DM"?

![Screenshot_2024-11-11-19-59-42-87_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/e22d8896-4f2a-45f9-b628-7adb9628dc34)

**Comment by enoch85** [comment]
And finally, my curve:

![IMG20241111200801](https://github.com/user-attachments/assets/9c8eef56-6b19-4c0d-8fac-c93d4ab4b88f)

**Comment by elden1337** [comment]
You might need to investigate at what dm you start the compressor on your nibe. It's a bit too low that it drops to -700 on a day like today. And given that your low dm setting in peaq is there then yes it will up the vent and scream the compressor to close to max levels causing high usage

**Comment by elden1337** [comment]
Try latest 3.1.8. I don't think it would do any difference here since I think it is some setting of yours that allows it to drop too low before starting the compressor, and then not making it and then vent starts and runs it too high. But you never know, only some stability fixes regarding offset.

**Comment by elden1337** [comment]
It indicates that it starts dropping and that the compressor is unable to par the need (heat the water sufficiently in the pipe) and therefore it drops even more and causes higher work freq. 

I can see that you do tolerance 3 which is fine. That should not cause this. 

Your house is larger than mine. Is your system aired recently?

**Comment by enoch85** [comment]
>  Is your system aired recently?

No, it was built 2022, and then nothing is done out of the ordinary. I increased the pressure in the tank to 1.7 bar, but other than that, no.

**Comment by elden1337** [comment]
> >  Is your system aired recently?
> 
> 
> 
> No, it was built 2022, and then nothing is done out of the ordinary. I increased the pressure in the tank to 1.7 bar, but other than that, no.
> 
> 

Ok. Then please check nibe docs on how to maint your system so that there's no air in the system.
