### ISSUE TITLE
Lower offset (or temp) if price too high

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#39]
Either with a maxprice in setup or if current price is rolling30avg * x

**Comment by enoch85** [comment]
Yes, something like this...

I don't use max price (I mean hard to guess what's a good value) so that should preferably be automated on an average, with spot prices for the next 24/48 hours taken in to account. Brainstorming here.

**Comment by elden1337** [comment]
Note to self, must be another maxprice than peaqevcore currently provides given master/slave between hvac/car
