### ISSUE TITLE
Create pre-heating based on day-pattern

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#41]
If all day tomorrow is expensive, heat some extra water before the increase to possibly avoid expensive heating

**Comment by enoch85** [comment]
Would love this!

I think this this should apply to the floor heating as well. In a well insulated house the heat will not vapor that fast, and a smaller need for heating the next day (or night). In other words, really use the low peaks in best possible way.

**Comment by elden1337** [comment]
![image](https://github.com/elden1337/hass-peaqhvac/assets/22585518/4c81abff-6b27-4e7b-b34c-7e98ed2860dd)

![image](https://github.com/elden1337/hass-peaqhvac/assets/22585518/97b35ae2-4326-417a-bef4-bad15f20cdee)
