### ISSUE TITLE
Make sensor and function for "periodisk höjning"

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#48]
Should be a restoreentity-sensor that survives reboots
On hitting limits it should make sure to heat water all the way to max temp.

**Comment by enoch85** [comment]
What's actually the "limits"?

I've had water at 15 degrees some days... I think when it hits 20 degrees it should boost as soon as possible within X minutes/hours, and if it doesn't find a time slot with low price then boost anyway.

**Comment by elden1337** [comment]
Are you sure about that? Lets say you are showering at 23 and noone else is awake. Why not boost at 4 in that case?

**Comment by enoch85** [comment]
I've set it to "economy" between 4:00 - 4:15. I haven't kept real track, but I've seen the temperature of the water being ~15 degrees. This is the last 24 hours:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/6fb0da7b-fd85-4d75-9be4-1c3cfeb5ac31)

**Comment by enoch85** [comment]
Yesterday I had to manually boost for my wife to take a shower, so I'm not sure it even boosts, even if it say it does.

The small rise in temperature at around 4:00 yesterday was when it was put in economy mode. Before that it was me with my manual boost.

**Comment by elden1337** [comment]
you did add read/write for the nibe integration when you set that one up right?

**Comment by enoch85** [comment]
Yes, it worked before. (2.0.2) but I have to double check. Been totally focused on getting a good setting for the home battery the last couple of days.

**Comment by enoch85** [comment]
Read/write is set, and was set.
