### ISSUE TITLE
Feature request: Add Energi Data Service

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#49]
Would be nice if you could add support for this https://github.com/MTrab/energidataservice

As per discord discussion.

**Comment by elden1337** [comment]
note to self: easiest is to move the whole spotprice module from peaqev to the core-repo and let peaqev, peaqhvac and peaqnext use the same module going forward. also move the broadcasting observertypes as they would be needed.

**Comment by elden1337** [comment]
- [ ] Add sensors for average-data and all the averagetypes to peaqhvac. Conditionally added if there is no peaqev to avoid duplicates.
- [ ] Add some sensor or attribute on peaqhvac stating the source of prices as is on peaqev-hourcontroller

**Comment by elden1337** [comment]
pushed a proposed change. however not done with sensors showing the averages etc so keeping this issue open for now. 
https://github.com/elden1337/hass-peaqhvac/releases/tag/2.0.4

**Comment by enoch85** [comment]
I've disabled Nordpool for a few days now, and it seems like it gets the price anyway, I think. 

We can reopen if it behaves abnormally.
