### ISSUE TITLE
Can't configure the integration

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#50]
### System

- HAOS 11 (tested both public and private access, right now it's set to be public) - installed like 1 week ago fresh, didn't touch anything except allowing `trusted_proxies` in `configuration.yaml`
- [Nibe integration](https://github.com/elupus/hass_nibe)
- peaq-hvaq 2.0.2
- Nibe F750
- Subscription to "Change Settings" in Nibe:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/4b550c86-ecda-4efd-a9bf-68834e721376)

### Debuggning

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/2896c3e7-5e3c-47e5-bbc0-aba8a45dbf3f)

The real sensor names are:
**Indoor temp**
`sensor.nibe_15XXXX_40033`

**Outdoor temp:**
`sensor.nibe_15XXXX_40004`

Tried using them as well, but first tried with only numbers since [that's what the documentation says](https://github.com/elden1337/hass-peaqhvac#nibe).

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/772feb1f-fe87-4b5f-a1d6-585fae52a300)

Is it here that I enable debuggning? Done in that case.

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/380b844d-ba8d-4910-bf9e-c6f3ec04d09d)

Sensors are working, but some of them are unavailable in the Nibe integration - don't know if that related?

**Comment by elden1337** [comment]
fix for peaqev_facade. let me know how far you get now and we'll keep this ticket open for a while @enoch85 
https://github.com/elden1337/hass-peaqhvac/releases/tag/2.0.3

**Comment by enoch85** [comment]
Woow, seems to work! :rocket: 

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/ecb30701-21c1-496e-bb41-e76249e19b46)

**Comment by enoch85** [comment]
Hmm, don't know about this though:

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/fc64a6d7-51ba-4206-81a1-9bcd31f45c7a)

Note: have reinstalled Nibe integration like 4 times now, maybe related?

**Comment by elden1337** [comment]
> Hmm, don't know about this though:
> 
> 
> 
> ![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/fc64a6d7-51ba-4206-81a1-9bcd31f45c7a)
> 
> 
> 
> Note: have reinstalled Nibe integration like 4 times now, maybe related?

Dont know what part of the system this is.

**Comment by enoch85** [comment]
> > Hmm, don't know about this though:
> > ![image](https://user-images.githubusercontent.com/4511254/277478824-fc64a6d7-51ba-4206-81a1-9bcd31f45c7a.png)
> > Note: have reinstalled Nibe integration like 4 times now, maybe related?
> 
> Dont know what part of the system this is.

Automations when clicking from inside the integration.

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/6cc8629d-6410-4623-9eef-4f8495a0657e)

**Comment by enoch85** [comment]
Sorry, false alarm, everything is there now. 

Please check discord for more questions, I will buy you a couple of beers for the help!
