### ISSUE TITLE
[Feature request] peak and consumption adoption without PeaqEV

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#51]
I think this app should be fully standalone from other Peaq-apps. Maybe make a a separate lib for the price adoption which all the apps could use? 

I already have a EV Smart charger and don't want another integration just for calculating spot peaks.

Love this so far, not even been 30 minutes. :D

**Comment by elden1337** [comment]
Sane request, but a large feature. Should do this
