### ISSUE TITLE
Scheduling?

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#52]
Please elaborate on: "For water i block as much as possble in nibe schedule (not blocking water pump) ) that is all but 15 min per 24h that cannot be blocked. And let peaq dictate it."

So what you're saying is that you let peaq decide on what to do for 15 minutes per 24 hours? That doesn't sound logical to me, I mean how can it even do something with those 15 minutes? I must be misunderstanding.

**Comment by elden1337** [comment]
No ;) the oposite. I block as much as i could schedulewise in my f730.

**Comment by enoch85** [comment]
When you say "block", do you mean that you set scheluding for hot water to "off" (don't make any hot water) between e.g. 00:00 - 23:45?

Or do you allow it ("economy mode") to procuce hot water between  00:00 - 23:45 and block (från) 23:45 - 23:59?

**Comment by elden1337** [comment]
yes, the later. but i do it 01-01:15 since it's often cheaper and more calm in the house then (this is a breach of logic i've had to do since it won't block all hours unless you block water possibilitiy alltogether and then boost wont work either.

**Comment by enoch85** [comment]
But with logic in place to "be smart" (only heat water when price is low) then there should be no need for blocking since it will only heat water when price is low anyway...?

Sorry, trying to get my head around this, which is a little bit "mos" since I've been awake late the past week.

**Comment by enoch85** [comment]
Also since you only allow it to hot water for 15 minutes, you effectively are bypassing the pevaq logic, since it's actually *you* who decides when to hot water or not. 

Just to be 100% clear here, is this what you mean?

00:00 - 01:00: block (hot water "off") 
01:00 - 02:00: produce hot water (hot water "economy") between 01:00 - 01:15.
02:00 - 03:00: block (hot water "från")
03:00 - 04:00: block (hot water "från")
04:00 - 05:00: block (hot water "från")
05:00 - 06:00: block (hot water "från")
06:00 - 07:00: block (hot water "från")
07:00 - 08:00: block (hot water "från")
08:00 - 09:00: block (hot water "från")
09:00 - 10:00: block (hot water "från")
10:00 - 11:00: block (hot water "från")
11:00 - 12:00: block (hot water "från")
12:00 - 13:00: block (hot water "från")
13:00 - 14:00: block (hot water "från")
14:00 - 15:00: block (hot water "från")
15:00 - 16:00: block (hot water "från")
16:00 - 17:00: block (hot water "från")
17:00 - 18:00: block (hot water "från")
18:00 - 19:00: block (hot water "från")
19:00 - 20:00: block (hot water "från")
20:00 - 21:00: block (hot water "från")
21:00 - 22:00: block (hot water "från")
22:00 - 23:00: block (hot water "från")
23:00 - 00:00: block (hot water "från")

**Comment by elden1337** [comment]
yepp, that's what i currently have it at.

**Comment by enoch85** [comment]
> yepp, that's what i currently have it at.

OK, but then it's not smart... It's manual. ;)

What I want is for pevaq to determine when it should produce hot water - when the price is low, and block the hot water producing other times. Maybe it's time for a feature request?

**Comment by elden1337** [comment]
No ;) it is determining when to boost depending on price and demand (demand is based on the current temp). 
The blockage is to not have the pump heat when i dont want it to.

**Comment by enoch85** [comment]
Aaaaaaaah, so pevaq bosts even if it's blocked in schedule? That would make sense. :)
