### ISSUE TITLE
[Feature request] A switch to decide how aggressive peak should be

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#53]
Like in Smart Price adoption, you can set it to high or low. Same thing would apply here. 

Names could be funnier though, like:
1. Normal
2. Eco
3. Eco+
4. Är du smålänning?

**Comment by elden1337** [comment]
Check number.peaqhvac_tolerance (i have it at 2, noticing larger savings on peakcharge than elprice, and the two will fight each other in their respective natures.

**Comment by enoch85** [comment]
I currently have it at 4. Will that be more agressive in terms of trying to hit the down peaks and the max out the compressor?

**Comment by elden1337** [comment]
it will only adjust the curve adjustment, but then it will give you more steps to play with (+4 - -4) depending on price-curve, but also your set temp and real temp, temp trend and temp extremas (in your case extremas is jsut the single sensor)

**Comment by elden1337** [comment]
but yes, the higher, the more lean towards price and less lean towards effektavgift

**Comment by elden1337** [comment]
this is my consumption so far today against the el-price. not super lean but peak for the month of 2.1kwh:

![image](https://github.com/elden1337/hass-peaqhvac/assets/22585518/b153f0d0-409c-4000-bdc3-511ff4c5c9a6)

**Comment by elden1337** [comment]
Already existing feature. Closing
