### ISSUE TITLE
[Feature request] Let pevaq set a schelude based on spot price

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#57]
As discussed in https://github.com/elden1337/hass-peaqhvac/issues/52 pevaq boosts the hot water even if the scheduling is turned off. It would be nice if pevaq also could *set* schedules based on then the price is low.

The benefit would be that if price is low over a period of time, it would be allowed to produce hot water during that time, and if price is high during a long period of time then add a block and don't even boost. Maybe boost could be used in a combination with the automatic scheduling as well...?

Anyway, I don't know if it even makes sense since we have boost in pevaq, but I figure that the boost only looks for short periods of time, and therefore put extra ware on the compressor/pump even if not needed (since it needs to peak the effect). It would be better from a "ware-perspective" to actually set a schedule and let the pump work on it's own.

The calculation should not be based (maybe as an option) on a fixed max and low setting, but on an average so that one don't have to care.

**Comment by elden1337** [comment]
Unfortunately declined due to very limited factors in nibe api. Already investigated this. All i can do is be as smart as possible about when to boost and when not to.

**Comment by enoch85** [comment]
OK, totally get that!
