### ISSUE TITLE
Latest water boost - restore entity

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#59]
Retain value over reboots to remember latest.

**Comment by enoch85** [comment]
I don't know if this is the same thing as I would report as a bug...

I never see when the latest boost happened. Noticed this last morning. I think it worked on version 2.0.2.

![Screenshot_2023-10-28-02-54-45-35_c3a231c25ed346e59462e84656a70e50](https://github.com/elden1337/hass-peaqhvac/assets/4511254/71fc1ab4-2378-4791-8efe-bdb5695ce2db)
![Screenshot_2023-10-28-05-42-58-20_c3a231c25ed346e59462e84656a70e50](https://github.com/elden1337/hass-peaqhvac/assets/4511254/b23254b6-1825-4fd0-9e32-b21e00bec34d)

**Comment by elden1337** [comment]
Could be. Wait a few days and see if it had improved. Otherwise another issue
