### ISSUE TITLE
[Feature request] Let end-user decide on Weather App

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#60]
Basically, let the end user decide on which weather app to use. I use [OpenWeatherMap](https://openweathermap.org/) for example. I also think that the default behavior of other apps are to let the user choose instead of making it a dependency.

Right now I've disabled weather (together with you) since it doesn't work at all in 2.0.6.  I think this should be a priority, but you decide.

**Comment by elden1337** [comment]
easiest would be to add a sensor input in setup that you can pick. what has to be determined though is that it can be parsed hourly so that i can work with it in an easy manner.

**Comment by enoch85** [comment]
Exactly. During first setup.

**Comment by enoch85** [comment]
Now when "Configure" is available, it should be easy to just add it there. :)

**Comment by elden1337** [comment]
> Now when "Configure" is available, it should be easy to just add it there. :)

semi. has to be rewritten since it's hardcoded to search in met-integration at the moment.
