### ISSUE TITLE
Averages are reset on every update

### ISSUE THREAD

**Issue by enoch85** [elden1337/hass-peaqhvac#62]
Since upgrading to 2.0.7 yesterday, all my averages are gone, and it's just like it started over again.

I'm not 100% sure, but I think I had more data than this before the update.

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/ce6cc65e-05f8-450d-bb66-771b32e0f441)

**Comment by elden1337** [comment]
This looks fine. The avg week must have seven days to work with, and avg month as many as the current month has consumed. Therefore they are 0 afaik. Three days not shown here should be an avg though.
