### ISSUE TITLE
offsets not correct

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#67]
![image](https://github.com/elden1337/hass-peaqhvac/assets/22585518/6e3b0e29-8d6c-450a-92b1-3cbd5fd2ec65)

prices: [0.36, 0.33, 0.33, 0.32, 0.33, 0.45, 0.96, 1.09, 1.29, 1.14, 0.98, 0.9, 0.93, 1.06, 1.21, 1.4, 1.67, 2.03, 2.21, 1.47, 1.22, 1.07, 0.73, 0.59]
tolerance: 2

**Comment by enoch85** [comment]
Just a reference with setting 3:

![Screenshot_2023-11-06-17-27-03-14_c3a231c25ed346e59462e84656a70e50](https://github.com/elden1337/hass-peaqhvac/assets/4511254/66e22af0-754d-4ba6-b768-9a10f7593095)

**Comment by enoch85** [comment]
Here are some more...

![image](https://github.com/elden1337/hass-peaqhvac/assets/4511254/b5d133c0-ff82-452d-b9cc-1938747f9ed5)


I think it should start later tomorrow, now it seems like it starts in the middle of the peak just because it's "one hack" down.
